### ISSUE TITLE
Possibility of using other vagrant box

### ISSUE THREAD

**Issue by orestesgaolin** [Dared87/dropbox-referral-accounts#1]
Hi, is it possible to use different vagrant box? I have a problem with logging into gnutix/ubuntu-trusty-dropbox-casperjs via ssh (perhaps virtualization issue) and I wonder what are requirements of vagrant box to run the script. As I can see in the box description it should be provided with Dropbox, PhantomJS & CasperJS. Could anyone give any details on its configuration?

Details:
I use current Virtualbox 5.1.6/Vagrant 1.8.5 with Mint 18 64bit on Virtualbox 5.1.6 on Windows 10, my processor supports VT-x
![virtualbox_mintdrop_13_09_2016_23_00_27](https://cloud.githubusercontent.com/assets/16854239/18506346/e79b0be4-7a6b-11e6-9a8b-d086836e70ea.png)

**Comment by Dared87** [comment]
I stumbled accross the same issue. If you try to start the Vbox via the GUI you would get an error like "VT-x/AMD-V hardware acceleration is not available on your system...". It looks like it is not possible to start a Vbox within a Vbox. I tested it again with "Windows 10 Host -> VMWare -> Windows 7 Guest -> VirtualBox -> Vagrantbox" and it at least started the virtual machine.

But I have to note, that this script is currently not working, because of this issue here at Bitbucket: https://bitbucket.org/gnutix/dropbox-referral-accounts/issues/1/consistent-timeout-when-checking-that-the

**Comment by orestesgaolin** [comment]
Thank you for the answer. I've also found this GUI error and went through many possible solutions to this - unfortunately with no positive effect. 

Sorry to read that. I think that I have to find another solution. Thanks for your work!
